version: '3.7'

services:
    app:
        image: node:lts
        restart: always
        user: ${HOST_USER_ID}
        labels:
            traefik.enable: true
            traefik.backend: ${TRAEFIK_PROJECT_NAME}-http
            traefik.frontend.rule: Host:${DOMAIN}
            traefik.docker.network: traefik
            traefik.port: ${APP_PORT}
        networks:
            - default
            - traefik
        env_file: .env
        volumes:
            - ./:/home/node/app
        working_dir: /home/node/app
        command: bash -c 'yarn install && yarn run demo:start'

networks:
    traefik:
        external:
            name: ${TRAEFIK_NETWORK_NAME}
